/**
 * Praksa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("WeatherForecastApi", () => {
  let instance: api.WeatherForecastApi
  beforeEach(function() {
    instance = new api.WeatherForecastApi(config)
  });

  test("weatherForecastGet", () => {
    return expect(instance.weatherForecastGet({})).resolves.toBe(null)
  })
})

